### ISSUE TITLE
Ephemeral messages - additional standard times

### ISSUE THREAD

**Issue by Morse6690** [olvid-io/olvid-android#17]
Really appreciate your work on this amazing tool.

The ephemeral message settings have options to delete after 1 day or 1 week, but nothing in between.

1. Would it be possible to add default times to include each day in between, ie 2,3,4,5,6 days?

2. If that is not possible or too cluttered then at least something in between like 3 days would be very useful.

Thanks again.

**Comment by finiasz** [comment]
Hi @Morse6690, thanks for your support! There are indeed a lot of options missing in this list, and the list is already very long. We need to change the way we pick these duration in the app.

We could add a few options, but this has to be done in sync with other versions of the app (the iOS version for now, but soon our desktop version too) as this setting is part of our backup, and we need to be sure backups are properly restored on all versions.

I'll see if we can work something out for you!

**Comment by finiasz** [comment]
We are currently working on an update to ephemeral settings. The goal is to improve the UI, and at the same time allow to pick a custom duration for all settings. Keep your eyes opened in the coming weeks 😁
