### ISSUE TITLE
Delete attachment for all users

### ISSUE THREAD

**Issue by Morse6690** [olvid-io/olvid-android#19]
On ios when a photo or file is deleted, the option to "delete for all users" appears. And the file is deleted from all devices. This happens whether the other device is ios or android.

Android does not seem to have this option.
The attachment can only be deleted from my device only. 

Is it possible to please add this feature?

**Comment by Naia-love** [comment]
you can delete attachements from all devices if u delete it msg (instead of holding on the picture, hold on the left of it and it'll select the msg) 
but its true that if the msg have more than one attachement or text, and u only want to remove one attachement. you indeed cannot as of now ^^;

**Comment by Morse6690** [comment]
Thanks for that. I'll give that a try.

**Comment by finiasz** [comment]
Hi @Morse6690, as @Naia-love pointed out, there is no option in Olvid to "delete everywhere" an attachment. Only a message can be deleted everywhere. And I agree, the UI is not very convenient as it is: we should offer the option to delete the whole message when long-pressing an attachment. Especially for messages that contain only an image!

We'll see to add this option in a future release.
