### ISSUE TITLE
android to ios: Restore of manual backup failed 

### ISSUE THREAD

**Issue by Morse6690** [olvid-io/olvid-android#21]
I am using the manual backup option and trying to transfer my account to a different device.
I manually exported on Android and transferred the file to my ios device. When restoring the key is accepted but a message appears: restore failed.....
I have tried several different backup files with no success.
Is this a known limitation?
Is there another setting I need to be using here?

**Comment by finiasz** [comment]
Hello @Morse6690, there should not be any limitation. We recently removed the compression that used to be applied to backups, so if you are using an old iOS version of the app, this could explain the problem, but if you are using the latest version, this should normally work.

Do you have access to the console logs of the app on your iOS device? This could help us understand the problem.

**Comment by Morse6690** [comment]
Apologies, I didn't have time to do this sooner. I believe recent updates have addressed this issue.
