### ISSUE TITLE
latest version also on GitHub

### ISSUE THREAD

**Issue by kumy** [olvid-io/olvid-android#22]
Hi,
I got a notification yesterday about a new version available. Apparently there was an update on Oct 9, 2023 on Google Play. May you please publish the code here also :pray:. Current published release is v1.15.0 from Jul 31.
![image](https://github.com/olvid-io/olvid-android/assets/176794/e9e07c2c-bbde-4c2b-8476-5a531fa53196)

**Comment by finiasz** [comment]
Yes, sorry, we have been in a rush lately. I'll do my best to update soon.

**Comment by finiasz** [comment]
Done, thanks for reminding me about this 😄
