### ISSUE TITLE
[Feature Request] accelérer les vocaux

### ISSUE THREAD

**Issue by C0wnuts** [olvid-io/olvid-android#25]
Comme sur Whatsapp, ajouter une fonctionnalité pour accélérer l'écoute des messages vocaux reçus et envoyés en: x1.25, x1.5, x2.

S'il vous plaît les vocaux de 7 minutes j'en peux plus x)

**Comment by finiasz** [comment]
Nous avons assez peu de retours sur les vocaux en général, donc merci beaucoup pour cette remarque ! Nous allons voir s'il est possible d'ajouter cela facilement (tout dépend de si le lecteur media natif Android propose cela).
