### ISSUE TITLE
Change the Git host from Github to a privacy respecting service.

### ISSUE THREAD

**Issue by git10700** [olvid-io/olvid-android#29]
I suggest moving the repo to any of the following hosts:

- [Codeberg](https://codeberg.org/explore/repos)
- [Gitlab](https://gitlab.com/explore)
- [Sourcehut](https://sr.ht/projects)
- [Gitea](https://gitea.com/explore/repos)

[Relevant link](https://giveupgithub.org/)

**Comment by finiasz** [comment]
Thanks for your suggestion, but GitHub is not our main development git repository. We only use it to publish snapshots of the versions we release to the store. We have no plan of changing this process at the moment.
