### ISSUE TITLE
Is it possible to add a copy/paste feature on messages ?!

### ISSUE THREAD

**Issue by yapalgit** [olvid-io/olvid-android#5]
It's a bit annoying that we can't copy a message and paste it somewhere else.

Thanks ! And I love Olvid ;) !

**Comment by gcovain** [comment]
Hello, 
You can do that by swiping the message left :-)
Swipe right to cite the message.

**Comment by finiasz** [comment]
Thanks @gcovain! Also, in the next release of Olvid you will be able to copy/paste both the text and attachments of a message instead of only the text (as this is currently the case).
