### ISSUE TITLE
New releases should always be shared on GitHub before the stores update

### ISSUE THREAD

**Issue by Naia-love** [olvid-io/olvid-android#9]
Just saw there's an update for Olvid on the play store (0.11.1 , from the 27/01 !?), I was pretty surprised seeing it as I didn't get any email from GitHub about new release on the code, and well yeah after checking here, you didn't shared the code of that new release here (yet?)??
I really think it should be before the update get on the stores

**Comment by finiasz** [comment]
Hello Naia-love, we do our best to publish the code to Github as soon as possible after an update, but after the publication of a new version on the store we always have to check before pushing anything to Github. In particular, we need to make sure we do not publish any confidential information or API key, and we need to clean up all our comments.

This time, we are running a bit late. Sorry for that! We hope you can wait a few more days.

**Comment by Naia-love** [comment]
bump, got an update on play store, but nothing here again x3

**Comment by PLAYERUNKNOWNHatsune01** [comment]
Yes! Still no update here on Github after their new release! The latest release was Sept 19 and now it's Oct 9. I wonder if Olvid was real open source app or just marketing buzz word, at least Telegram did a good job than this application releasing their code. Yes Telegram still late to release their code BUT NOT THIS LONG! I'll make a Reddit post about this topic given warning to people who might consider using this app. I don't know if the devs are few or something but this application is kinda fishy.

**Comment by finiasz** [comment]
Hello everyone, sorry for not being very reactive to your messages. Nothing fishy about the app, we simply are a small dev team and are sometimes overwhelmed by the amount of things to do.

If you only want to install Olvid from the sources provided here, feel free to do so! Updating your app with a few weeks delay surely is not a big deal.

**Comment by kumy** [comment]
Wondering what are the reasons to not have the main dev repo public?

**Comment by 002gRTEah3mRYH** [comment]
0.13.0, same

I feel like that app isn't really open source tho, by seeing other issues and comments

**Comment by Naia-love** [comment]
bumb
Got yet another update on google and not here

**Comment by finiasz** [comment]
Here is the latest version of the code, corresponding to version 0.13.0 available on the store.

**Comment by kumy** [comment]
Thanks @finiasz for this new release!! :tada: 

However I cannot pass the unit tests (see #13). Am I the only one?
